---
title: "EDA"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## California Housing Prices

```{r}
housing <- read.csv("housing.csv")

housing$total_bedrooms[is.na(housing$total_bedrooms)] = median(housing$total_bedrooms , na.rm = TRUE)

housing$mean_bedrooms = housing$total_bedrooms/housing$households
housing$mean_rooms = housing$total_rooms/housing$households

drops = c('total_bedrooms', 'total_rooms')

housing = housing[ , !(names(housing) %in% drops)]
colnames(housing)
```
## Kolumny

* longitude - długość geograficzna 
* latitude - szerokość geograficzna 
* housing median age - wiek domu
* total rooms - liczba pomieszczeń w mieszkaniu
* total bedrooms - liczba sypialni w mieszkaniu
* population - populacja miejscowości 
* 

```{r}
head(housing)
```

```{r}
library(ggplot2)
library(DataExplorer)
library(ggpubr)

columns <- names(housing)
columns <- columns[-8]

DataExplorer::plot_density(housing)

count_plot <- ggplot(housing, aes(ocean_proximity)) +
  geom_bar(colour="black", fill = "grey") +
  theme_pubclean()

count_plot

```

```{r}
library(corrplot)

DataExplorer::plot_correlation(housing)

```

```{r}
us <- c(left = min(housing$longitude), bottom = min(housing$latitude), 
        right = max(housing$longitude), top = max(housing$latitude))
p <- get_stamenmap(us, zoom = 7, maptype = "toner-lite") %>% ggmap() 

p + geom_point(aes(x = longitude, y = latitude), data = housing, size = 0.5, color = "red")

p + geom_point(aes(x = longitude, y = latitude,  colour = ocean_proximity), data = housing, size = 0.5) + 
  theme(legend.position="bottom") 

p + geom_point(aes(x = longitude, y = latitude, colour = median_house_value), data = housing, alpha=0.25, size = 0.75) + 
  theme(legend.position="bottom") + 
  scale_color_gradient2(midpoint=mean(housing$median_house_value), low="green", mid="yellow",
                        high="red", space ="Lab" )
```

